import type { Product } from "@/lib/catalogue/types";

/** MTDC product list supplied on 6 October 2026. Descriptions approved by MTDC on 6 October 2026. Sizes are preserved as supplied; no stock, manufacturer, carton, channel or ingredient claims are inferred. Rice and charcoal brands are intentionally unset. The four featured entries are a provisional display selection. Photos await approved assets. */
export const products: Product[] = [
  {
    id: "zyn-vegetable-oil-25kg",
    slug: "zyn-vegetable-oil-25kg",
    name: "Vegetable Oil 25 kg",
    categoryId: "cooking-oils",
    description:
      "Zyn vegetable oil in a 25 kg pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: true,
    channels: [],
    packSize: "25 kg",
    brandId: "zyn",
    subcategoryId: "vegetable-oil",
  },
  {
    id: "zyn-soya-oil-25kg",
    slug: "zyn-soya-oil-25kg",
    name: "Soya Oil 25 kg",
    categoryId: "cooking-oils",
    description:
      "Zyn soya oil in a 25 kg pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "25 kg",
    brandId: "zyn",
    subcategoryId: "soya-oil",
  },
  {
    id: "zyn-soya-oil-1l",
    slug: "zyn-soya-oil-1l",
    name: "Soya Oil 1 L",
    categoryId: "cooking-oils",
    description:
      "Zyn soya oil in a 1 L pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: true,
    channels: [],
    packSize: "1 L",
    brandId: "zyn",
    subcategoryId: "soya-oil",
  },
  {
    id: "zyn-soya-oil-1-7l",
    slug: "zyn-soya-oil-1-7l",
    name: "Soya Oil 1.7 L",
    categoryId: "cooking-oils",
    description:
      "Zyn soya oil in a 1.7 L pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "1.7 L",
    brandId: "zyn",
    subcategoryId: "soya-oil",
  },
  {
    id: "zyn-soya-oil-5l",
    slug: "zyn-soya-oil-5l",
    name: "Soya Oil 5 L",
    categoryId: "cooking-oils",
    description:
      "Zyn soya oil in a 5 L pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "5 L",
    brandId: "zyn",
    subcategoryId: "soya-oil",
  },
  {
    id: "rice-25kg",
    slug: "rice-25kg",
    name: "Rice 25 kg",
    categoryId: "rice-grains",
    description:
      "Rice in a 25 kg pack size, supplied by MTDC to trade buyers in Abuja / FCT. Brand and variety are to be confirmed; ask our team for current details when you request a quote.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "25 kg",
  },
  {
    id: "rice-50kg",
    slug: "rice-50kg",
    name: "Rice 50 kg",
    categoryId: "rice-grains",
    description:
      "Rice in a 50 kg pack size, supplied by MTDC to trade buyers in Abuja / FCT. Brand and variety are to be confirmed; ask our team for current details when you request a quote.",
    images: [],
    availability: "unconfirmed",
    featured: true,
    channels: [],
    packSize: "50 kg",
  },
  {
    id: "lamoure-tomato-paste-50g",
    slug: "lamoure-tomato-paste-50g",
    name: "Tomato Paste 50 g",
    categoryId: "tomato-paste",
    description:
      "Lamoure tomato paste in a 50 g pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "50 g",
    brandId: "lamoure",
  },
  {
    id: "lamoure-tomato-paste-210g",
    slug: "lamoure-tomato-paste-210g",
    name: "Tomato Paste 210 g",
    categoryId: "tomato-paste",
    description:
      "Lamoure tomato paste in a 210 g pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "210 g",
    brandId: "lamoure",
  },
  {
    id: "lamoure-tomato-paste-400g",
    slug: "lamoure-tomato-paste-400g",
    name: "Tomato Paste 400 g",
    categoryId: "tomato-paste",
    description:
      "Lamoure tomato paste in a 400 g pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: true,
    channels: [],
    packSize: "400 g",
    brandId: "lamoure",
  },
  {
    id: "lamoure-tomato-paste-2-2kg",
    slug: "lamoure-tomato-paste-2-2kg",
    name: "Tomato Paste 2.2 kg",
    categoryId: "tomato-paste",
    description:
      "Lamoure tomato paste in a 2.2 kg pack size, supplied by MTDC to trade buyers in Abuja / FCT. Request a quote with the quantity you need and your delivery area.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    packSize: "2.2 kg",
    brandId: "lamoure",
  },
  {
    id: "rima-markouk-bread",
    slug: "rima-markouk-bread",
    name: "Markouk Bread",
    categoryId: "bread-bakery",
    description:
      "Rima markouk bread, available from MTDC in different types for trade buyers in Abuja / FCT. Types and pack sizes are to be confirmed; tell us which type you need when you request a quote.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
    brandId: "rima",
  },
  {
    id: "shisha-charcoal",
    slug: "shisha-charcoal",
    name: "Shisha Charcoal",
    categoryId: "charcoal",
    description:
      "Charcoal supplied by MTDC to trade buyers in Abuja / FCT. Brand, type and pack sizes are to be confirmed; ask our team for current details when you request a quote.",
    images: [],
    availability: "unconfirmed",
    featured: false,
    channels: [],
  },
];
