import type { Product } from "@/lib/catalogue/types";

/** MTDC product list supplied on 6 October 2026. Descriptions are drafts. Sizes are preserved as supplied; no stock, manufacturer, carton, channel or ingredient claims are inferred. Rice and charcoal brands are intentionally unset. The four featured entries are a provisional display selection. Photos await approved assets. */
export const products: Product[] = [
  {
    "id": "zyn-vegetable-oil-25kg",
    "slug": "zyn-vegetable-oil-25kg",
    "name": "Vegetable Oil 25 kg",
    "categoryId": "cooking-oils",
    "description": "Draft description: Vegetable Oil 25 kg. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": true,
    "channels": [],
    "packSize": "25 kg",
    "brandId": "zyn",
    "subcategoryId": "vegetable-oil"
  },
  {
    "id": "zyn-soya-oil-25kg",
    "slug": "zyn-soya-oil-25kg",
    "name": "Soya Oil 25 kg",
    "categoryId": "cooking-oils",
    "description": "Draft description: Soya Oil 25 kg. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "25 kg",
    "brandId": "zyn",
    "subcategoryId": "soya-oil"
  },
  {
    "id": "zyn-soya-oil-1l",
    "slug": "zyn-soya-oil-1l",
    "name": "Soya Oil 1 L",
    "categoryId": "cooking-oils",
    "description": "Draft description: Soya Oil 1 L. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": true,
    "channels": [],
    "packSize": "1 L",
    "brandId": "zyn",
    "subcategoryId": "soya-oil"
  },
  {
    "id": "zyn-soya-oil-1-7l",
    "slug": "zyn-soya-oil-1-7l",
    "name": "Soya Oil 1.7 L",
    "categoryId": "cooking-oils",
    "description": "Draft description: Soya Oil 1.7 L. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "1.7 L",
    "brandId": "zyn",
    "subcategoryId": "soya-oil"
  },
  {
    "id": "zyn-soya-oil-5l",
    "slug": "zyn-soya-oil-5l",
    "name": "Soya Oil 5 L",
    "categoryId": "cooking-oils",
    "description": "Draft description: Soya Oil 5 L. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "5 L",
    "brandId": "zyn",
    "subcategoryId": "soya-oil"
  },
  {
    "id": "rice-25kg",
    "slug": "rice-25kg",
    "name": "Rice 25 kg",
    "categoryId": "rice-grains",
    "description": "Draft description: Rice 25 kg. Brand and rice variety are to be confirmed. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "25 kg"
  },
  {
    "id": "rice-50kg",
    "slug": "rice-50kg",
    "name": "Rice 50 kg",
    "categoryId": "rice-grains",
    "description": "Draft description: Rice 50 kg. Brand and rice variety are to be confirmed. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": true,
    "channels": [],
    "packSize": "50 kg"
  },
  {
    "id": "lamoure-tomato-paste-50g",
    "slug": "lamoure-tomato-paste-50g",
    "name": "Tomato Paste 50 g",
    "categoryId": "tomato-paste",
    "description": "Draft description: Tomato Paste 50 g. Brand spelling is supplied by MTDC and awaits packaging confirmation. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "50 g",
    "brandId": "lamoure"
  },
  {
    "id": "lamoure-tomato-paste-210g",
    "slug": "lamoure-tomato-paste-210g",
    "name": "Tomato Paste 210 g",
    "categoryId": "tomato-paste",
    "description": "Draft description: Tomato Paste 210 g. Brand spelling is supplied by MTDC and awaits packaging confirmation. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "210 g",
    "brandId": "lamoure"
  },
  {
    "id": "lamoure-tomato-paste-400g",
    "slug": "lamoure-tomato-paste-400g",
    "name": "Tomato Paste 400 g",
    "categoryId": "tomato-paste",
    "description": "Draft description: Tomato Paste 400 g. Brand spelling is supplied by MTDC and awaits packaging confirmation. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": true,
    "channels": [],
    "packSize": "400 g",
    "brandId": "lamoure"
  },
  {
    "id": "lamoure-tomato-paste-2-2kg",
    "slug": "lamoure-tomato-paste-2-2kg",
    "name": "Tomato Paste 2.2 kg",
    "categoryId": "tomato-paste",
    "description": "Draft description: Tomato Paste 2.2 kg. Brand spelling is supplied by MTDC and awaits packaging confirmation. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "packSize": "2.2 kg",
    "brandId": "lamoure"
  },
  {
    "id": "rima-markouk-bread",
    "slug": "rima-markouk-bread",
    "name": "Markouk Bread",
    "categoryId": "bread-bakery",
    "description": "Draft description: Markouk Bread. Different types are supplied; type names and pack sizes are to be confirmed. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "brandId": "rima"
  },
  {
    "id": "shisha-charcoal",
    "slug": "shisha-charcoal",
    "name": "Shisha Charcoal",
    "categoryId": "shisha-accessories",
    "description": "Draft description: Shisha Charcoal. Brand, charcoal type and pack sizes are to be confirmed. Carton configuration and availability are to be confirmed.",
    "images": [],
    "availability": "unconfirmed",
    "featured": false,
    "channels": [],
    "subcategoryId": "charcoal"
  }
];
